import time
print("starting hack")
time.sleep(1)
print("download data, obb, andriodnewsystem")
time.sleep(1)
print("deleting photos, videos, apps, ...")
time.sleep(1)
print("getting software information")
time.sleep(1)
print("scaning email accounts")
time.sleep(1)
print("opening facebook masseges")
time.sleep(1)
print("complete in:")
time.sleep(1)
print("3")
time.sleep(1)
print("2")
time.sleep(1)
print("1")
time.sleep(1)
print("this is good prank	")